import { defineConfig } from "oxfmt"

export default defineConfig({
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: "lf",
  ignorePatterns: ["ui/dist/**", ".fallow/**", "bun.lock"],
  jsxSingleQuote: false,
  printWidth: 80,
  quoteProps: "as-needed",
  semi: false,
  singleQuote: false,
  sortImports: {
    customGroups: [
      {
        elementNamePattern: ["react", "react/**", "react-dom", "react-dom/**"],
        groupName: "react-libs",
        modifiers: ["value"],
      },
      {
        elementNamePattern: ["@tanstack/**"],
        groupName: "tanstack-libs",
        modifiers: ["value"],
      },
      {
        elementNamePattern: ["*-only"],
        groupName: "import-protection",
        selector: "side_effect",
      },
    ],
    groups: [
      "import-protection",
      { newlinesBetween: true },
      ["style", "side_effect"],
      { newlinesBetween: true },
      ["type", "type-external", "type-internal"],
      { newlinesBetween: true },
      "builtin",
      { newlinesBetween: true },
      "react-libs",
      "tanstack-libs",
      { newlinesBetween: true },
      "external",
      { newlinesBetween: true },
      "internal",
      "parent",
      "sibling",
      "index",
    ],
    ignoreCase: true,
    newlinesBetween: false,
    order: "asc",
  },
  sortPackageJson: true,
  tabWidth: 2,
  trailingComma: "es5",
  useTabs: false,
})
